{% set name = "git-secret" %}
{% set version = "0.2.5" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sobolevn/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 02224b360ef560d1a41ae758d16ef2f2657af8424711d52443ca7ac01367ad29

build:
  number: 1000

requirements:
  build:
    - make
    - posix  # [win]
  run:
    - git
    - gawk  # [not win]
    - m2-gnupg  # [win]
    - m2-gawk   # [win]

test:
  commands :
    - bash -c 'git secret --version'
    - bash -c 'test $(git secret --version) = {{ version }}'

about:
  home: https://git-secret.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'git-secret stores your private data inside a git repo'

  description: |
    git-secret is a bash tool to store your private data inside a git repo. 
    It encrypts tracked files using gpg with the public keys of all the users 
    that you trust. So everyone of them can decrypt these files using only 
    their personal secret key.
  doc_url: https://git-secret.io
  dev_url: https://github.com/sobolevn/git-secret

extra:
  recipe-maintainers:
    - sodre
