{% set name = "git-secret" %}
{% set version = "0.2.3" %}
{% set sha256 = "c821c25865ce7e13a67453debb6d60a8c1730102ecfc4c4b4c4858a02201ab26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sobolevn/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - posix  # [win]
    - toolchain
  run:
    - git
    - m2-gnupg  # [win]

test:
  commands :
    - bash -c 'test $(git secret --version) = {{ version }}'

about:
  home: https://git-secret.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'git-secret stores your private data inside a git repo'

  description: |
    git-secret is a bash tool to store your private data inside a git repo. 
    It encrypts tracked files using gpg with the public keys of all the users 
    that you trust. So everyone of them can decrypt these files using only 
    their personal secret key.
  doc_url: https://git-secret.io
  dev_url: https://github.com/sobolevn/git-secret

extra:
  recipe-maintainers:
    - sodre
