travis:
  secure:
    BINSTAR_TOKEN: hvprxYmQ8X76KRFX/yMf+u7rKwPtAHI2z8rpns493cyXXvWowpyKo4oe9WwuHrF89XA9dYhJ70K+Il/WdwTlb6wT1MJIuw3HCAodVLv6HOcCm1Eww0jOpLFw3O51U6UISvvsXECpSPGMSyrvXJryoAm4614SjPRR+Y0y7czz9oWlqFjK1a9uu1dmXzrjTpF1IYu60Dq3oEc9U8tpLel+2TpvHExeIlGQ8wEKXbHL1XQHFkt8HfYRdTaJEpjvJODFMvgqywA3IwzuwpmnEFCEG5dHu+q+gQFPIEehP4pNOsoCiDd5J8nrNkoo2kQbWUrlmKlzvjpG2mUNPEHk16AJIvNC+2rmp3mfXs+L14tsdam2Bt0rXpEFKff9AFrZeNpUbmEI7EtEDaw1CYHRgXsGibg8nITa/qiHgm1gOphkS7CnCe8n0zSEWGL9CscLcLthpl4cwEhQpeNF+XSLa2oCQz66Hq2Ts0Bx2+jsVmALhIhCDI96oWXM23i76nttK/HdcgaiWrEr+nTOlY1NKhE4b2Baf0X5tOKwngUKE66e/RuM7hkH2gCn6kNVB+IrfKUY0RjHzGD99pqe9knDkuiWZfF7W7/JuiCfiKUyQazCEsCuFzeqYvoSji7UMXoVOXCJHgFoug0kp+qXBsx25NyH0g1O0RHw0C2APxSHroelpho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
