travis:
  secure:
    BINSTAR_TOKEN: gEOvRFAAEqZJM2LHVZfP4ClLEyOhhYs1xfP8yt0cOa4zjS1uKv95SQhXfcazhElIzuCyf9o+NRJINhzyjQuJ9TT06d14TCW3Xymk0Nx8ven6cS4PCvTO4ZzzXufpu2V97i/yF7jiyoUSzipAi6MqzvkKM/9Of9C9NI1foiUi2fgl1tlbWrz34eo812IRzDcOvgExvSbnL4O6khEvhA/XO6IuGnbBvvlwgRqzgajK3TP+De2ZUNVZxzo+ssWvHg7fOAQCMIqI0CfGE2iQLtHIaFFa8ZTaI5iNjlX0LhlSzreORv1eBsJ8wTVm6dnYQZlBasGyqHoy5otZswenjcjDThtApvx3SzWDe7Z3cOjNz2wf+IJyG4dam51Yfm4+qOu8PSA6DNVSL0hUJKqSxZftXBrlzRhxjazUA2Umu1P6NtcZVjNOxqF6GS7rpBaHv6ySYyLRbivmOOUOn/TQ6e+nII2rSNecq2nzLy9f8jQ4XCgaFfZretEWv3jy1hGqt3iJf1u+P3qV3ywuzhcTFE8MQJW/2pAYyeSvhs4+X0ncFky4PnyfxT4Y4TRzwapnL06LEhg4QO0x9GySOYvtLd8dpWrU9aYjOtgeikKve+pH25cynnUqfxdAUt47Efmu3p6chLjaB4XFAydjmvKx/XSvQqwOAiRf0y7XxNBMzPvCnkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
